Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 108, in <module>
    lines2.append(str(fitness[x-2]) +"," + str(error[x-2]) + '\n')
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_fitness_chi.py", line 106, in <module>
    lines2.append(str(lines[x]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/data_write.py", line 110, in <module>
    f5.write( individual[i] +', '+ chi[i] +', '+ fitness[i] +', '+ error[i] +', '+ parent1[i] +', '+ parent2[i] +', '+ opperator[i] +', '+ \
IndexError: list index out of range
Traceback (most recent call last):
  File "/tmp/slurmtmp.12807233/test_plotter.py", line 27, in <module>
    max_scores.append(max(scores))
ValueError: max() arg is an empty sequence
mv: cannot stat 'fitness.png': No such file or directory
